global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'transaction-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['transaction-service:80']
        
  - job_name: 'account-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['account-service:80']
        
  - job_name: 'logging-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['logging-service:80']